# ============ Default (producción) ============
spring:
  application:
    name: PositionGeofence
  data:
    mongodb:
      uri: mongodb://localhost:27017/mcs_position_geofence
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8080
  forward: ""

# logging: niveles por paquete
logging:
  level:
    root: INFO
    com.traccar.PositionGeofence: DEBUG   # aquí activas DEBUG para todo tu código
    org.springframework: INFO             # (opcional) bajar ruido de Spring

# Resto tu configuración…  
traccar:
  use-environment-variables: false
  protocols: gps103,tk103,osmand
  gps103:
    port: 5001
  tk103:
    port: 5002
  osmand:
    port: 5055  
  web:
    path: "./web"
    debug: false
    console: false
  geocoder:
    type: "locationiq"
  media:
    path: "./media"
  logger:
    console: false
    queries: false
    full-stack-traces: false
    protocol:
      name: "PositionGeofence"
  mail:
    debug: false
  database:
    driver: "com.mongodb.MongoDriver"
    url: "mongodb://localhost:27017/mcs_position_geofence"
  atrack:
    custom: false
  intellitrac:
    port: 0

logger:
  attributes: time,position,speed,course,accuracy,result

gateway:
  device:
    baseUrl: http://localhost:8082/api
  user:
    baseUrl: http://localhost:8082/api
  notification:
    baseUrl: http://localhost:8082/api
  server:
    baseUrl: http://localhost:8082/api

# …

# ============ Perfil DEBUG ============  
---
spring:
  config:
    activate:
      on-profile: debug

logging:
  level:
    root: DEBUG         # a nivel global levanta todo a DEBUG
    com.traccar.PositionGeofence: TRACE

traccar:
  web:
    console: true       # si quieres que Traccar engine pinte su propio log
  logger:
    console: true       # imprime en stdout
    full-stack-traces: true

# … otros overrides que ya tenías comentados