spring:
  application:
    name: PositionGeofence
  data:
    mongodb:
      uri: mongodb://localhost:27017/mcs_position_geofence
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8080
  forward: ""

# Configuración global (perfil "default", es decir, producción)
traccar:
  use-environment-variables: false
  web:
    path: "./web"
    debug: false
    console: false
  geocoder:
    type: "locationiq"
  media:
    path: "./media"
  logger:
    console: false
    queries: false
    full-stack-traces: false
    protocol:
      name: "PositionGeofence"
  mail:
    debug: false
  database:
    driver: "com.mongodb.MongoDriver"
    url: "mongodb://localhost:27017/mcs_position_geofence"
  atrack:
    custom: false
  intellitrac:
    port: 0


logger:
  attributes: time,position,speed,course,accuracy,result
---
# # Configuración para el perfil "debug"
# spring:
#   config:
#     activate:
#       on-profile: debug

# traccar:
#   use-environment-variables: true
#   web:
#     # Uso del tema simple que aparece en el debug.xml original
#     path: "./traccar-web/simple"
#     debug: true
#     console: true
#   geocoder:
#     type: "pluscodes"
#   media:
#     path: "./target/media"
#   logger:
#     console: true
#     queries: false
#     full-stack-traces: true
#   mail:
#     debug: true
#   database:
#     # En modo debug se usa la configuración para H2 según el debug.xml
#     driver: "org.h2.Driver"
#     url: "jdbc:h2:./target/database"
#     user: "sa"
#     password: ""
#   atrack:
#     custom: true
#   intellitrac:
#     port: 6037

# Configuración para el Gateway (aplica para todos los perfiles)
gateway:
  device:
    baseUrl: https://demo.traccar.org/api  # Cambia a la URL real de tu servicio
  user:
    baseUrl: https://demo.traccar.org/api
  notification:
    baseUrl: https://demo.traccar.org/api
  server:
    baseUrl: https://demo.traccar.org/api

system:
  properties:
    net.fortuna.ical4j.timezone.cache.impl: net.fortuna.ical4j.util.MapTimeZoneCache

broadcast:
  exchange: traccarExchange
  routing-key: broadcast

